### ISSUE TITLE
Local branch name

### ISSUE THREAD

**Issue by kwankyu** [sagemath/trac-to-github#175]
Of course, there is no rule on naming local branches. It is up to the user's preference. However, from my recent experiences, I think we can be helpful to a newcomer (like me) by suggesting a fixed form for naming local branches corresponding to issues/prs.  

In trac, we had "t/123456/make-sage-great". Similarly I suggest "fix#123456/make-sage-great"  as local branch name for issue/pr #123456.

If we can agree on this, I may update the workflow doc accordingly.

**Comment by mkoeppe** [comment]
I think that's a good idea for PRs that correspond to existing Issues. 
But for PRs that do not fix existing issues, it does not make sense because at the time of creating the branch, one does not want to guess the PR number of the PR that is to be created.
Also we should not include the special character `#`, which would need quoting in the shell.
So something like "issue/123456/faster-transmogrification" could work.

**Comment by kwankyu** [comment]
> for PRs that do not fix existing issues, it does not make sense because at the time of creating the branch, one does not want to guess the PR number of the PR that is to be created. 

Right. I missed the situation.

> Also we should not include the special character `#`, which would need quoting in the shell. So something like "issue/123456/faster-transmogrification" could work.

A scheme that does not apply to PRs seems just confusing. I will give up.
