### ISSUE TITLE
Take Trac and cgit servers offline

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/trac-to-github#80]
- either host all of trac.sagemath.org in static readonly mode (e.g. via github pages) forever to preserve links from external websites (suggested by @williamstein )
- or set up http permanent redirects to the Issues (ticket numbers & issue numbers map 1:1, and fragments (`#comment:...`) continue to work)

**Comment by kwankyu** [comment]
> * or set up http permanent redirects to the Issues (ticket numbers & issue numbers map 1:1, and fragments (`#comment:...`) continue to work)

+1

**Comment by williamstein** [comment]
I just did some checking, and doing this will save us nearly $3K/year!   The sooner the better.

**Comment by williamstein** [comment]
@robertwb points out in an email that Cython did this via making one page for each ticket that does the redirect.  Here's their code:

https://github.com/cython/cython.github.io/blob/master/trac/ticket/1.html

I don't have a clue about this since it looks like Ruby-on-Rails, etc.

**Comment by williamstein** [comment]
There's a little bit of confusion and nobody taking this, and I'm actually personally paying for the $300/month right now, so I'm going to take this issue and deal with it, one way or another.

**Comment by williamstein** [comment]
OK, this is now done.  There's a new repo here:

https://github.com/sagemath/trac.sagemath.org

In it, you'll find a script "generate.py" that generates very simple little pages with links to the github and web archive.   I didn't implement any automatic redirect at all, for simplicity, and since a person might reasonably want to visit either github or the web archive.   In case anybody wants to change the contents of those pages (or add some more redirects from other url's), you have to checkout the repo, then do:
```sh
python ./generate.py
```
then commit and push it back.  When you push it, the page https://trac.sagemath.org  will be automatically updated within 10 minutes.  This is a simple static website hosted by GitHub Pages, configured [here](https://github.com/sagemath/trac.sagemath.org/settings/pages).
